version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
   - pip install sphinx>=8.1.3,<9 furo>=2024.8.6,<2025 sphinx-copybutton>=0.5.2,<1 discord.py>=2.3.2
   - cd docs; python -m sphinx-build -aEnT --keep-going . $READTHEDOCS_OUTPUT
   # - python -m sphinx -T -E -b html -d _build/doctrees -D language=en ./docs $READTHEDOCS_OUTPUT/html

sphinx:
   configuration: docs/conf.py

python:
   install:
   - requirements: docs/requirements.txt
