version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
   - python -m pip install --upgrade -r docs/requirements.txt
   - python -m sphinx -aEnTW --builder html --keep-going docs/ $READTHEDOCS_OUTPUt/html

sphinx:
   configuration: docs/conf.py

python:
   install:
   - requirements: docs/requirements.txt
