blank_issues_enabled: false
contact_links:
  - name: Ask a question
    about: Ask questions and discuss with other users of the library.
    url: https://github.com/No767/discord-ext-ipcx/discussions