name: Lint
on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  Check:
    name: Check (${{ matrix.version }})
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        version: ['3.10', '3.11', '3.12', '3.13']

    env:
      UV_NO_DEV: true
      UV_NO_DEFAULT_GROUPS: true

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Python ${{ matrix.version }}
        id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --group lint

      - name: Check typing
        run: |
          uv run ty check discord/ext/ipcx --error-on-warning

      - name: Check codebase
        run: |
          uv run ruff check discord/ext/ipcx --exit-non-zero-on-fix

      - name: Check for formatting
        run: |
          uv run ruff format discord/ext/ipcx --check