name: Lint
on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  Check:
    name: Check (${{ matrix.version }})
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    env:
      UV_NO_BUILD: true
      UV_NO_DEV: true
      UV_NO_DEFAULT_GROUPS: true

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@8.1.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --group lint

      - name: Check typing
        run: |
          uv run pyright discord/ext/ipcx examples

      - name: Check codebase
        run: |
          uv run ruff check discord/ext/ipcx examples --exit-non-zero-on-fix

      - name: Check for formatting
        run: |
          uv run ruff format discord/ext/ipcx examples --check