name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    runs-on: ubuntu-24.04

    if: contains(github.event.head_commit.message, '#major') || contains(github.event.head_commit.message, '#minor') || contains(github.event.head_commit.message, '#patch')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Generate release notes
      uses: no767/get-releasenote@v0
      with:
        name: discord-ext-ipcx
        changes_file: changelog.md
        output_file: output.md
        version_file: discord/ext/ipcx/__init__.py

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      id: tag_version
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        
    - name: Release New Version
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "output.md"
        token: ${{ secrets.RELEASE_TOKEN }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: ${{ steps.tag_version.outputs.new_tag }}