name: Towncrier
on:     
  pull_request:
    branches:
      - main

jobs:
  Check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Towncrier
        run: |
          pip install "towncrier>=24.8.0,<25"
          
      - name: Verify Towncrier entry added
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          towncrier check